version: '3.8'
services:
  app:
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ./workspace:/workspace:cached

    command: /bin/sh -c "while sleep 1000; do :; done"
 
